# Generated by Django 3.2.4 on 2021-07-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210701_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateogry',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcateogry',
            new_name='subcategory',
        ),
    ]
